<? session_start();
if(!$_SESSION['login']){
    header('Location: auth.php');
}

require "blocks/header.php";?>

        <div class="content">
            <div class="container">
                <div class="content_text">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Placerat in egestas erat imperdiet sed euismod nisi. Elementum pulvinar etiam non quam. Massa massa ultricies mi quis hendrerit dolor. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Arcu bibendum at varius vel pharetra vel. Eu turpis egestas pretium aenean. Sapien nec sagittis aliquam malesuada bibendum. Integer feugiat scelerisque varius morbi enim nunc. Est velit egestas dui id ornare. Odio aenean sed adipiscing diam donec adipiscing tristique. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Eu mi bibendum neque egestas congue quisque. Viverra nam libero justo laoreet sit amet. A pellentesque sit amet porttitor. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Accumsan sit amet nulla facilisi morbi. Bibendum at varius vel pharetra vel turpis nunc eget. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Quis blandit turpis cursus in hac habitasse platea dictumst quisque. Sagittis id consectetur purus ut faucibus pulvinar elementum integer. Felis eget velit aliquet sagittis. Dictumst quisque sagittis purus sit amet. Iaculis at erat pellentesque adipiscing. Quis viverra nibh cras pulvinar mattis. Mi in nulla posuere sollicitudin. Consequat id porta nibh venenatis cras sed felis eget velit. Mi tempus imperdiet nulla malesuada pellentesque elit. Adipiscing elit duis tristique sollicitudin. At tempor commodo ullamcorper a lacus vestibulum sed. Duis tristique sollicitudin nibh sit amet. Convallis tellus id interdum velit laoreet id donec. Tempus iaculis urna id volutpat lacus laoreet non curabitur. Adipiscing bibendum est ultricies integer quis auctor elit. Amet mauris commodo quis imperdiet massa tincidunt. Sed viverra ipsum nunc aliquet bibendum. Congue eu consequat ac felis donec et. Viverra adipiscing at in tellus integer feugiat scelerisque. Porta lorem mollis aliquam ut porttitor. Erat velit scelerisque in dictum non consectetur. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Egestas sed tempus urna et pharetra. Mus mauris vitae ultricies leo integer malesuada nunc vel. Malesuada fames ac turpis egestas maecenas pharetra. Aliquet nec ullamcorper sit amet risus nullam eget felis eget. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Lacinia quis vel eros donec ac odio tempor. Nullam ac tortor vitae purus faucibus ornare suspendisse sed. Nulla aliquet porttitor lacus luctus accumsan tortor posuere. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Placerat in egestas erat imperdiet sed euismod nisi. Elementum pulvinar etiam non quam. Massa massa ultricies mi quis hendrerit dolor. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Arcu bibendum at varius vel pharetra vel. Eu turpis egestas pretium aenean. Sapien nec sagittis aliquam malesuada bibendum. Integer feugiat scelerisque varius morbi enim nunc. Est velit egestas dui id ornare. Odio aenean sed adipiscing diam donec adipiscing tristique. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Eu mi bibendum neque egestas congue quisque. Viverra nam libero justo laoreet sit amet. A pellentesque sit amet porttitor. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Accumsan sit amet nulla facilisi morbi. Bibendum at varius vel pharetra vel turpis nunc eget. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Quis blandit turpis cursus in hac habitasse platea dictumst quisque. Sagittis id consectetur purus ut faucibus pulvinar elementum integer. Felis eget velit aliquet sagittis. Dictumst quisque sagittis purus sit amet. Iaculis at erat pellentesque adipiscing. Quis viverra nibh cras pulvinar mattis. Mi in nulla posuere sollicitudin. Consequat id porta nibh venenatis cras sed felis eget velit. Mi tempus imperdiet nulla malesuada pellentesque elit. Adipiscing elit duis tristique sollicitudin. At tempor commodo ullamcorper a lacus vestibulum sed. Duis tristique sollicitudin nibh sit amet. Convallis tellus id interdum velit laoreet id donec. Tempus iaculis urna id volutpat lacus laoreet non curabitur. Adipiscing bibendum est ultricies integer quis auctor elit. Amet mauris commodo quis imperdiet massa tincidunt. Sed viverra ipsum nunc aliquet bibendum. Congue eu consequat ac felis donec et. Viverra adipiscing at in tellus integer feugiat scelerisque. Porta lorem mollis aliquam ut porttitor. Erat velit scelerisque in dictum non consectetur. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Egestas sed tempus urna et pharetra. Mus mauris vitae ultricies leo integer malesuada nunc vel. Malesuada fames ac turpis egestas maecenas pharetra. Aliquet nec ullamcorper sit amet risus nullam eget felis eget. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Lacinia quis vel eros donec ac odio tempor. Nullam ac tortor vitae purus faucibus ornare suspendisse sed. Nulla aliquet porttitor lacus luctus accumsan tortor posuere. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum.
                    </p>
                </div>
            </div>
        </div>
        
<? require "blocks/footer.php"; ?>

   